### ISSUE TITLE
CTA in iFrame for API in Public Dashboard page

### ISSUE THREAD

**Issue by realchoubey** [dapplooker/analyzer#38]
https://www.notion.so/dapplooker/Chart-and-Dashboard-API-as-Dedicated-CTA-21cf366c4c194aab914ea353c7d0584f

**Comment by realchoubey** [comment]
- [ ] CardID issue
- [ ] Dashboard <> Card mapping issue

**Comment by KESHAVsCODE** [comment]
- Added a link to navigate to the Create API keys page.
- Now only logged-in users in the analyzer can see an API button on all charts of a Dashboard.
- Users are not able to access the chart API button on charts of public embeded dashboards on daplooker website.
