### ISSUE TITLE
Allow users to make chart and dashboard public from analyzer

### ISSUE THREAD

**Issue by realchoubey** [dapplooker/analyzer#40]
- Problem: Users are not able to make chart/dashboard public. The don't have public discover url.

- In Analyzer, add CTA on below pages
   - Analyzer chart details page
   - Analyzer dashboard details page

- CTA can be like API button. on click of API, chart/dashboard gets public and users gets public discover url

**Comment by realchoubey** [comment]
- [ ] Public
- [ ] Private
- [ ] Beside API button
- [ ] Same icon
- [ ] Reuse Page
- [ ] If Admin or creator

**Comment by hitesh23k** [comment]
- [ ] Chart/Dashboard publish API implementation and Integration
